route:
  group_by: ['alertname']
  # group_by: ['InstanceStatus']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 10m
  receiver: 'web.hook'
receivers:
- name: 'web.hook'
  webhook_configs:
  # - url: 'http://192.168.8.35:8081/webhook'
  - url: 'http://192.168.8.35:8060/dingtalk/webhook_mention_users/send'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
