global:
  scrape_interval: 60s  # 每隔多少秒抓取一次
  evaluation_interval: 60s  # 设定每多少秒评估告警规则

# 指定告警配置文件目录
rule_files:
  - "/etc/prometheus/rules.yaml"

# 配置alertmanager的地址
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: "prod-ua-gateway"
    static_configs:
    - targets: ["api.xinfei.cn"]
    metrics_path: /ua-api/metrics